---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[broken::default]
    attributes:
  - name: firewall
    run_list:
      - recipe[broken::firewall]
